// examples/react/src/App.tsx
import { useState } from "react";
import { AutocompleteInput } from "@tomickigrzegorz/autocomplete-react";
import "@tomickigrzegorz/autocomplete/css";
import "./app.css";

const API =
  "https://raw.githubusercontent.com/tomickigrzegorz/autocomplete/master/docs/characters.json";

type Character = { name: string; actor: string; picture: string };

async function fetchCharacters(): Promise<Character[]> {
  const res = await fetch(API);
  return res.json();
}

export default function App() {
  const [selected, setSelected] = useState<Character | null>(null);

  const onSearch = async ({ currentValue }: { currentValue: string }) => {
    const data = await fetchCharacters();
    return data
      .sort((a, b) => a.name.localeCompare(b.name))
      .filter((el) => el.name.match(new RegExp(currentValue, "gi")));
  };

  const onResults = ({
    currentValue,
    matches,
  }: {
    currentValue: string;
    matches: Character[];
  }) =>
    matches
      .map(
        (el) => `
        <li>
          <img src="${el.picture}" alt="${el.name}" width="32" height="32" />
          <p>${el.name.replace(new RegExp(currentValue, "gi"), (s) => `<b>${s}</b>`)}</p>
          <small>${el.actor}</small>
        </li>`,
      )
      .join("");

  const onSubmit = ({ object }: { object: Character }) => {
    setSelected(object);
  };

  return (
    <div className="container">
      <h1>
        <span className="badge">React</span> Autocomplete demo
      </h1>
      <p className="hint">Breaking Bad characters — type a name</p>

      <div className="auto-search-wrapper">
        <AutocompleteInput
          onSearch={onSearch}
          onResults={onResults}
          onSubmit={onSubmit}
          placeholder="e.g. Walter"
        />
      </div>

      {selected && (
        <div className="selected-card">
          <img src={selected.picture} alt={selected.name} />
          <div>
            <strong>{selected.name}</strong>
            <span>played by {selected.actor}</span>
          </div>
        </div>
      )}
    </div>
  );
}

// examples/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { AutocompleteComponent } from "@tomickigrzegorz/autocomplete-angular";

interface Character {
  name: string;
  actor: string;
  picture: string;
}

const API =
  "https://raw.githubusercontent.com/tomickigrzegorz/autocomplete/master/docs/characters.json";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, AutocompleteComponent],
  template: `
    <div class="container">
      <h1>
        <span class="badge">Angular</span> Autocomplete demo
      </h1>
      <p class="hint">Breaking Bad characters — type a name</p>

      <div class="auto-search-wrapper">
        <ngx-autocomplete
          [onSearch]="onSearch"
          [onResults]="onResults"
          [onSubmit]="onSubmit"
          placeholder="e.g. Walter"
        />
      </div>

      <div class="selected-card" *ngIf="selected">
        <img [src]="selected.picture" [alt]="selected.name" />
        <div>
          <strong>{{ selected.name }}</strong>
          <span>played by {{ selected.actor }}</span>
        </div>
      </div>
    </div>
  `,
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  selected: Character | null = null;

  onSearch = async ({ currentValue }: { currentValue: string }) => {
    const res = await fetch(API);
    const data: Character[] = await res.json();
    return data
      .sort((a, b) => a.name.localeCompare(b.name))
      .filter((el) => el.name.match(new RegExp(currentValue, "gi")));
  };

  onResults = ({
    currentValue,
    matches,
  }: {
    currentValue: string;
    matches: Character[];
  }) =>
    matches
      .map(
        (el) => `
        <li>
          <img src="${el.picture}" alt="${el.name}" width="32" height="32" />
          <p>${el.name.replace(new RegExp(currentValue, "gi"), (s) => `<b>${s}</b>`)}</p>
          <small>${el.actor}</small>
        </li>`,
      )
      .join("");

  onSubmit = ({ object }: { object: Character }) => {
    this.selected = object;
  };
}
