// packages/react/src/index.tsx
import { useEffect, useId, useRef } from "react";
import Autocomplete, {
  type AutocompleteOptions,
} from "@tomickigrzegorz/autocomplete";

// every callback is delegated — also those passed only after mount
const CALLBACK_KEYS = [
  "onSearch",
  "onResults",
  "onSubmit",
  "onOpened",
  "onReset",
  "onRender",
  "onClose",
  "noResults",
  "onLoading",
  "onSelectedItem",
] as const;

type Callback = (...args: unknown[]) => unknown;

export type AutocompleteProps = AutocompleteOptions & {
  className?: string;
  placeholder?: string;
  "aria-label"?: string;
};

export function AutocompleteInput({
  className,
  placeholder,
  "aria-label": ariaLabel,
  ...options
}: AutocompleteProps) {
  const ref = useRef<HTMLInputElement>(null);
  // strip characters invalid in id/attribute names (React 17/18 ":r0:", React 19 "«r0»")
  const uid = useId().replace(/[^a-zA-Z0-9_-]/g, "");
  const optionsRef = useRef(options);
  optionsRef.current = options;

  // empty deps — the instance lives for the component lifetime
  useEffect(() => {
    if (!ref.current) return;

    // callbacks delegate through optionsRef, so the instance always calls
    // the latest props without being destroyed and re-created on re-renders
    const liveOptions: Record<string, unknown> = { ...optionsRef.current };
    for (const key of CALLBACK_KEYS) {
      liveOptions[key] = (...args: unknown[]) =>
        (optionsRef.current[key] as Callback | undefined)?.(...args);
    }

    const instance = new Autocomplete(
      ref.current,
      liveOptions as unknown as AutocompleteOptions,
    );

    return () => instance.unmount();
  }, []);

  return (
    <input
      ref={ref}
      id={uid}
      type="text"
      className={className}
      placeholder={placeholder}
      aria-label={ariaLabel}
    />
  );
}

export default AutocompleteInput;

// packages/svelte/src/index.svelte
<script lang="ts">
import { untrack } from "svelte";
import Autocomplete, {
  type AutocompleteOptions,
} from "@tomickigrzegorz/autocomplete";

// every callback is delegated — also those passed only after mount
const CALLBACK_KEYS = [
  "onSearch",
  "onResults",
  "onSubmit",
  "onOpened",
  "onReset",
  "onRender",
  "onClose",
  "noResults",
  "onLoading",
  "onSelectedItem",
] as const;

type Callback = (...args: unknown[]) => unknown;

type Props = AutocompleteOptions & {
  class?: string;
  placeholder?: string;
};

const props: Props = $props();

let inputEl: HTMLInputElement;

$effect(() => {
  // untrack — the instance lives for the component lifetime; callbacks
  // delegate through the live rune props, so they always call the latest
  // prop without the instance being re-created
  const instance = untrack(() => {
    // placeholder and class belong to the <input>, not to the core
    const {
      class: _class,
      placeholder: _placeholder,
      ...options
    } = props as Record<string, unknown>;
    for (const key of CALLBACK_KEYS) {
      options[key] = (...args: unknown[]) =>
        (props[key] as Callback | undefined)?.(...args);
    }
    return new Autocomplete(inputEl, options as unknown as AutocompleteOptions);
  });

  return () => instance.unmount();
});
</script>

<input
  bind:this={inputEl}
  type="text"
  class={props.class}
  placeholder={props.placeholder}
/>
